import { TextField, Typography, RadioGroup, FormControlLabel, Radio, Autocomplete } from "@mui/material";
import React from "react";
import Card from '../Card';
import './passo1.css';


export default function Passo1(props) {
    const profissoes = [
        {id: "5207", label: "Açougueiro "},
        {id: "5217", label: "Acrobata "},
        {id: "5206", label: "Adestrador "},
        {id: "10034", label: "Adestrador De Cachorro "},
        {id: "10035", label: "Adestrador De Cavalo "},
        {id: "5022", label: "Administrador De Empresa "},
        {id: "21230", label: "Administradores De Tecnologia Da Informação"},
        {id: "131", label: "Advogado"},
        {id: "72130", label: "Afiadores E Polidores De Metais "},
        {id: "595", label: "Agen.D/Serv.Funerarios embals "},
        {id: "405", label: "Agenciador De Propaganda "},
        {id: "5221", label: "Agente "},
        {id: "292", label: "Agente Administrativo "},
        {id: "594", label: "Agente D/Viagem E Guia Turism "},
        {id: "35220", label: "Agentes Da Saude E Do Meio Ambiente "},
        {id: "9028", label: "Agentes De Seguranca(Armados) = Guarda Costa "},
        {id: "9030", label: "Agentes De Seguranca(Desarmados) = Guarda Costa "},
        {id: "35230", label: "Agentes Fiscais Metrologicos E De Qualidade "},
        {id: "10119", label: "Agricultores "},
        {id: "103", label: "Agrônomo "},
        {id: "71700", label: "Ajudantes De Obras Civis "},
        {id: "72500", label: "Ajustadores Mecanicos Polivalentes "},
        {id: "591", label: "Alfaiate "},
        {id: "78420", label: "Alimentadores De Linhas De Producao "},
        {id: "41410", label: "Almoxarifes E Armazenistas "},
        {id: "126", label: "Analista De Sistema "},
        {id: "35430", label: "Analistas De Comercio Exterior "},
        {id: "71570", label: "Aplicadores De Materiais Isolantes "},
        {id: "71650", label: "Aplicadores De Revestimentos Ceramicos, Pastilhas, Pedras E Madeiras "},
        {id: "41420", label: "Apontadores E Conferentes "},
        {id: "923", label: "Aposentado "},
        {id: "37630", label: "Apresentadores De Eventos, Programas E Espetaculos "},
        {id: "37720", label: "Arbitros Desportivos "},
        {id: "3", label: "Arqueólogo "},
        {id: "102", label: "Arquiteto "},
        {id: "40", label: "Arquivista "},
        {id: "26130", label: "Arquivistas E Museologos "},
        {id: "75110", label: "Artesaos De Metais Preciosos E Semi-Preciosos "},
        {id: "2", label: "Artista De Circo Em Geral "},
        {id: "26240", label: "Artistasvisuais, Desenhistas Industriais E Conservadores-Restauradores De Bens Culturais "},
        {id: "60", label: "Assistente Em Geral "},
        {id: "134", label: "Assistente Social "},
        {id: "51670", label: "Astrologos E Numerologos "},
        {id: "128", label: "Astrônomo E Meteorologista "},
        {id: "10036", label: "Atividadesrelacionadas A Cana De Acucar "},
        {id: "168", label: "Atleta Profiss.Tecnicodespor "},
        {id: "162", label: "Ator E Diretor/Espetáculos "},
        {id: "26250", label: "Atores "},
        {id: "5026", label: "Atuario "},
        {id: "5027", label: "Auditor "},
        {id: "25420", label: "Auditores Fiscais Da Pprevidencia Social "},
        {id: "25430", label: "Auditores Fiscais Do Trabalho "},
        {id: "25410", label: "Auditores Fiscais E Eecnicos Da Receita Federal "},
        {id: "41", label: "Auxiliar Administrativo "},
        {id: "394", label: "Auxiliar D/Escritório E Assem "},
        {id: "596", label: "Auxiliar De Laboratorio "},
        {id: "10120", label: "Baba/ Cuidador Deidosos "},
        {id: "395", label: "Bancário E Economiário "},
        {id: "135", label: "Bibliotecário, Arquivista E Etc. "},
        {id: "116", label: "Biólogo E Biomédico "},
        {id: "10037", label: "Biologos-Marinhos "},
        {id: "22120", label: "Biomedicos "},
        {id: "5239", label: "Bombeiro "},
        {id: "10111", label: "Boxe "},
        {id: "511", label: "Cabeleireiro,Barbeiro,Manicure "},
        {id: "2120", label: "Cabos E Soldados Dapolicia Militar "},
        {id: "5", label: "Caçadores Em Geral "},
        {id: "42", label: "Caixa "},
        {id: "163", label: "Cantor E Compositor "},
        {id: "2020", label: "Capitaes Da Policiamilitar "},
        {id: "907", label: "Capitalista,Rec.Rend.Aplic.Cap "},
        {id: "10122", label: "Carcereiro "},
        {id: "5208", label: "Carpinteiro "},
        {id: "77720", label: "Carpinteiros Decarrocerias E Carretas "},
        {id: "77710", label: "Carpinteiros Navais "},
        {id: "63260", label: "Carvoejadores "},
        {id: "26230", label: "Cenografos "},
        {id: "75230", label: "Ceramistas (Preparacaoe Fabricacao "},
        {id: "84220", label: "Charuteiros "},
        {id: "391", label: "Chefe Intermediário "},
        {id: "27110", label: "Chefes De Cozinha Eafins "},
        {id: "51360", label: "Churrasqueiros,Pizzaiolos E Sushimen "},
        {id: "10123", label: "Ciclista Amador "},
        {id: "10121", label: "Ciclista Profissional "},
        {id: "84210", label: "Cigarreiros Ebeneficiadores De Fumo "},
        {id: "42130", label: "Cobradores E Afins "},
        {id: "42120", label: "Coletadores De Apostase De Jogos "},
        {id: "31170", label: "Coloristas "},
        {id: "183", label: "Comandante De Embarcações "},
        {id: "10039", label: "Comerciante/Comerciario "},
        {id: "5041", label: "Comissario De Avarias "},
        {id: "182", label: "Comissário De Bordo "},
        {id: "136", label: "Comunicólogo "},
        {id: "78280", label: "Condutores De Animaise De Veiculos De Tracao Animal e pedais"},
        {id: "51150", label: "Condutores De Turismo "},
        {id: "78110", label: "Condutores Deprocessos Robotizados "},
        {id: "77640", label: "Confeccionadores Deartefatos De Madeira, Moveis"},
        {id: "74210", label: "Confeccionadores Deinstrumentos Musicais "},
        {id: "99110", label: "Conservadores De Viaspermanentes (Trilhos "},
        {id: "124", label: "Contador "},
        {id: "41220", label: "Continuos "},
        {id: "533", label: "Contramestre Deembarcacoes "},
        {id: "10040", label: "Coquerias "},
        {id: "165", label: "Coreografo E Bailarino "},
        {id: "7", label: "Correspondente De Guerra "},
        {id: "403", label: "Corretor/Imoveis, Seguros, Tit "},
        {id: "35450", label: "Corretores De Seguros "},
        {id: "25330", label: "Corretores De Valores,Ativos Financeiros, Mercadorias E Derivativos "},
        {id: "43", label: "Costureira "},
        {id: "44", label: "Cozinheiro "},
        {id: "63130", label: "Criadores De Animaisaquaticos "},
        {id: "10041", label: "Cross Country "},
        {id: "37610", label: "Dancarinostradicionais E Populares "},
        {id: "193", label: "Decorador "},
        {id: "24240", label: "Defensores Publicos E Procuradores Assistencia Judiciaria- "},
        {id: "214", label: "Delegado De Policia "},
        {id: "491", label: "Demonstrador "},
        {id: "10095", label: "Dentista "},
        {id: "192", label: "Desenhista Comercial "},
        {id: "105", label: "Desenhista Industrial "},
        {id: "31810", label: "Desenhistas Tecnicosda Construcao Civil Arquitetura"},
        {id: "31830", label: "Desenhistas Tecnicosem Eletricidade, Eletronica,Eletromecanica, Calefacao, Ventilacao Erefrigeracao "},
        {id: "31870", label: "Desenhistas Projetistas Da Eletronica "},
        {id: "31860", label: "Desenhistas Projetistas Da Mecanica "},
        {id: "31850", label: "Desenhistas Projetistas De Construcao Civil Arquitetura"},
        {id: "31880", label: "Desenhistas Projetistas E Modelistas De Produtos E Servicos Diversos "},
        {id: "318410", label: "Desenhista técnico/Tatuador "},
        {id: "37510", label: "Designers De Interiores, De Vitrines E Visual Merchandisere Afins (Nivel Medio"},
        {id: "593", label: "Despachante, Inclusive Aduanei "},
        {id: "34220", label: "Despachantes Aduaneiros "},
        {id: "8", label: "Detetive "},
        {id: "212", label: "Diplomata "},
        {id: "301", label: "Diretor De Empresas "},
        {id: "144", label: "Diretor Estabelecimestabelecem. De Ensino "},
        {id: "12230", label: "Diretores De Operacoesde Obras Em Empresa Construcao"},
        {id: "12260", label: "Diretores De Operacoesde Servicos Em Empresa Dearmazenamento, De Transporte E De Telecomunicacao "},
        {id: "12270", label: "Diretores De Operacoesde Servicos Em Instituicao Deintermediacao Financeira "},
        {id: "12370", label: "Diretores De Pesquisae Desenvolvimento "},
        {id: "12210", label: "Diretores De Producaoe Operacoes Em Empresa Agropecuaria,Pesqueira , Aquicola E Florestal "},
        {id: "12320", label: "Diretores De Recursoshumanos E Relacoes De Trabalho "},
        {id: "12360", label: "Diretores De Servicosde Informatica "},
        {id: "12330", label: "Diretores Decomercializacao E Marketing "},
        {id: "12380", label: "Diretores Demanutencao "},
        {id: "12340", label: "Diretores Desuprimentos E Afins "},
        {id: "13110", label: "Diretores E Gerentesde Operacoes Em Empresa De Servicospessoais, Sociais E Culturais "},
        {id: "13120", label: "Diretores E Gerentesde Operacoes Em Empresas E Unidades Desaude E Afins "},
        {id: "12310", label: "Diretoresadministrativos E Financeiros "},
        {id: "11410", label: "Dirigentes De Partidospoliticos "},
        {id: "11300", label: "Dirigentes De Povosindigenas, De Quilombolas Caicaras"},
        {id: "11140", label: "Dirigentes Do Servicopublico "},
        {id: "11420", label: "Dirigentes Eadministradores De Entidades Patronais E Dostrabalhadores E De Outrosinteresses Socioeconomicos "},
        {id: "11430", label: "Dirigentes Eadministradores De Entidades Religiosas "},
        {id: "11440", label: "Dirigentes Eadministradores De Organizacoes Da Sociedadecivil Sem Fins Lucrativos "},
        {id: "5205", label: "Do Lar, Dona De Casa "},
        {id: "10042", label: "Domadores Animaisdomesticos "},
        {id: "10043", label: "Domadores Animaisselvagens "},
        {id: "121", label: "Economista "},
        {id: "26160", label: "Editores "},
        {id: "10044", label: "Elaboracao Decombustiveis Nucleares "},
        {id: "542", label: "Eletricis.Manu.Veic.Auto.Elet "},
        {id: "703", label: "Eletricista Eassemelhados "},
        {id: "10045", label: "Eletricistas Baixatensao "},
        {id: "95110", label: "Eletricistas Demanutencao Eletroeletronica "},
        {id: "598", label: "Empregado Domestico "},
        {id: "161", label: "Empresário E Produtor Espetaculo "},
        {id: "76870", label: "Encadernadores Erecuperadores De Livros (Pequenos Lotes Oua Unidade "},
        {id: "5212", label: "Encanador "},
        {id: "113", label: "Enfermeiro "},
        {id: "101", label: "Engenheiro "},
        {id: "5001", label: "Engenheiro Aeronautico "},
        {id: "8015", label: "Engenheiro Agronomo "},
        {id: "5003", label: "Engenheiro Civil "},
        {id: "5011", label: "Engenheiro De Seg. Dotrabalho "},
        {id: "5004", label: "Engenheiro Eletricista "},
        {id: "5005", label: "Engenheiro Eletronico "},
        {id: "5006", label: "Engenheiro Industrial "},
        {id: "5007", label: "Engenheiro Mecanico "},
        {id: "5008", label: "Engenheiro Metalurgico "},
        {id: "5009", label: "Engenheiro Naval "},
        {id: "5010", label: "Engenheiro Quimico "},
        {id: "21400", label: "Engenheiros Ambientaise Afins "},
        {id: "21470", label: "Engenheiros De Minas Eafins "},
        {id: "22220", label: "Engenheiros Dealimentos E Afins "},
        {id: "20210", label: "Engenheiros Decontrole E Automacao, Engenheirosmecatronicos E Afins "},
        {id: "21220", label: "Engenheiros Emcomputacao "},
        {id: "21480", label: "Engenheirosagrimensores E Engenheiros Cartografos "},
        {id: "32500", label: "Enologos, Perfumistase Aromistas "},
        {id: "47", label: "Entregador "},
        {id: "42410", label: "Entrevistadores Erecenseadores "},
        {id: "10046", label: "Escafandristas "},
        {id: "41320", label: "Escriturarios Deservicos Bancarios "},
        {id: "191", label: "Escultor, Pintor E Assemelhados "},
        {id: "51680", label: "Esotericos Eparanormais "},
        {id: "34210", label: "Especialistas Emlogistica De Transportes "},
        {id: "35410", label: "Especialistas Empromocao De Produtos E Vendas "},
        {id: "10047", label: "Especiologista "},
        {id: "9", label: "Espeleologista "},
        {id: "949", label: "Espolio "},
        {id: "48", label: "Estagiario "},
        {id: "122", label: "Estatístico "},
        {id: "49", label: "Esteticista "},
        {id: "597", label: "Estivador,Carreg.Embal.Asseme "},
        {id: "10", label: "Estudante De 1 E 2 Grau "},
        {id: "11", label: "Estudante Universitário "},
        {id: "63230", label: "Extrativistasflorestais De Especies Produtoras De Fibras,Ceras E Oleos "},
        {id: "63220", label: "Extrativistasflorestais De Especies Produtoras De Gomas E Resinas"},
        {id: "63250", label: "Extrativistasflorestais De Especies Produtoras De Substancias Aromaticas, Medicinais Etoxicas "},
        {id: "63240", label: "Extrativistasflorestais De Especies Produtoras Dealimentos Silvestres "},
        {id: "10048", label: "Fabricacao De Armas Defogo E Municoes "},
        {id: "10049", label: "Fabricacao De Gasesnaturais "},
        {id: "10050", label: "Fabricacao Deintermediarios Para Fertilizantes "},
        {id: "117", label: "Farmacêutico "},
        {id: "55558", label: "Faxineiro "},
        {id: "10124", label: "Fazendeiro "},
        {id: "413", label: "Feirante "},
        {id: "72110", label: "Ferramenteiros E Afins "},
        {id: "25140", label: "Filosofos "},
        {id: "25440", label: "Fiscais De Tributosestaduais E Municipais "},
        {id: "51120", label: "Fiscais E Cobradoresdos Transportes Coletivos "},
        {id: "106", label: "Físico "},
        {id: "5073", label: "Físico-Químico "},
        {id: "114", label: "Fisioterapeuta E Terapeuta "},
        {id: "118", label: "Fonoaudiólogo "},
        {id: "10051", label: "Formulas Em Geral(Formula 1, Indy, Light, Mundial, Etc "},
        {id: "555556", label: "Fotografo (Aerea,Maritima E Submarina "},
        {id: "555555", label: "Fotografo (Excetoaerea, Maritima, Submarinaecorrespondente De Guerra "},
        {id: "555557", label: "Fotografo(Correspondente De Guerra "},
        {id: "10129", label: "Frentista "},
        {id: "922", label: "Funcion.Publico Civilaposent "},
        {id: "10052", label: "Funcionarios Publicosou Privados, Atua Emdelegaciasoupresidios"},
        {id: "50", label: "Garcom E Matrie "},
        {id: "605", label: "Garimpeiro "},
        {id: "127", label: "Geografo "},
        {id: "107", label: "Geólogo "},
        {id: "303", label: "Gerente "},
        {id: "14270", label: "Gerentes De Manutencaoe Afins "},
        {id: "14130", label: "Gerentes De Obras Emempresa De Construcao "},
        {id: "14160", label: "Gerentes De Operacoesde Servicos Em Empresa De Transporte,De Comunicacao E De Logistica (Armazenageme Distribuicao "},
        {id: "14150", label: "Gerentes De Operacoesde Servicos Em Empresa De Turismo, Dealojamento E Alimentacao "},
        {id: "14170", label: "Gerentes De Operacoesde Servicos Em Instituicao Deintermediacao Financeira "},
        {id: "14260", label: "Gerentes De Pesquisa Edesenvolvimento E Afins "},
        {id: "14110", label: "Gerentes De Producao Eoperacoes Em Empresa Agropecuaria,Pesqueira, Aquicola E Florestal "},
        {id: "14120", label: "Gerentes De Producao Eoperacoes Em Empresa Da Industriaextrativa, De Transformacao E De Servicos Deutilidade Publica "},
        {id: "14220", label: "Gerentes De Recursoshumanos E De Relacoes Do Trabalho "},
        {id: "14250", label: "Gerentes De Tecnologiada Informacao "},
        {id: "14240", label: "Gerentes Desuprimentos E Afins "},
        {id: "14210", label: "Gerentesadministrativos, Financeiros, De Riscos E Afins "},
        {id: "71640", label: "Gesseiros "},
        {id: "11150", label: "Gestores Publicos "},
        {id: "521", label: "Governantad/Hotel,Camareiro "},
        {id: "10053", label: "Guardas Municipais "},
        {id: "51140", label: "Guias De Turismo "},
        {id: "5222", label: "Inspetor "},
        {id: "5204", label: "Inspetor De Risco "},
        {id: "61", label: "Inspetor De Seguranca "},
        {id: "33410", label: "Inspetores De Alunos Eafins "},
        {id: "76180", label: "Inspetores E Revisoresde Producao Textil "},
        {id: "72570", label: "Instaladores Deequipamentos De Refrigeracao Ventilacao"},
        {id: "52310", label: "Instaladores Deprodutos E Acessorios "},
        {id: "95130", label: "Instaladores Emantenedores De Sistemas Eletroeletronicosdeseguranca "},
        {id: "95410", label: "Instaladores Emantenedores Eletromecanicos Deelevadores,Escadas E Portas Automaticas "},
        {id: "10054", label: "Instaladores Oucolocador De Antenas "},
        {id: "73130", label: "Instaladores-Reparadores De Linhas E Equipamentos De Telecomunicacoes "},
        {id: "23320", label: "Instrutores De Ensinoprofissional "},
        {id: "12", label: "Instrutores De Seguranca "},
        {id: "33310", label: "Instrutores Eprofessores De Cursos Livres "},
        {id: "5102", label: "Invest. Acidentesaeronauticos "},
        {id: "5101", label: "Investigador "},
        {id: "10128", label: "Jardineiro "},
        {id: "10113", label: "Jiu-Jitsu Judo(Somente Por Prazer, Profissional Ou Competicao"},
        {id: "717", label: "Joalheiros E Ourives "},
        {id: "412", label: "Jornaleiro "},
        {id: "171", label: "Jornalista "},
        {id: "62", label: "Juizesjuízes/ Magistrados "},
        {id: "10055", label: "Kart "},
        {id: "81810", label: "Laboratoristasindustriais Auxiliares "},
        {id: "5209", label: "Laminador "},
        {id: "10056", label: "Lanchas, Jetski(Prazer Ou Competicao "},
        {id: "543", label: "Lantern.E Pintorveicu.Metali "},
        {id: "51640", label: "Lavadores E Passadoresde Roupa, A Mao "},
        {id: "11110", label: "Legisladores "},
        {id: "404", label: "Leiloeiro, Avaliador, Assemelh "},
        {id: "10057", label: "Limpeza Urbana Eesgoto E Atividades Conexas "},
        {id: "166", label: "Locutor Ecomentar.D/Radio,Tv "},
        {id: "91910", label: "Lubrificadores "},
        {id: "10058", label: "Lutador De Vale Tudo "},
        {id: "14", label: "Lutador E Pugilista,Profissional Ou Amador, Ainda Queinstrutor, Nas Modalidades (Boxe, Judo,Jiu-Jitsu "},
        {id: "51", label: "Manicure E Pedicure "},
        {id: "10116", label: "Manipulador Desubstancias Corrosivas, Ou Explosivas- "},
        {id: "10108", label: "Mantenedores Deemissarios Submarinos "},
        {id: "99120", label: "Mantenedores Deequipamentos De Parques De E Similares- "},
        {id: "535", label: "Maquinista E Foguistad/Embar "},
        {id: "5213", label: "Marceneiro "},
        {id: "534", label: "Marinheiro E Assemelhados "},
        {id: "52", label: "Massagista "},
        {id: "63", label: "Matematico "},
        {id: "702", label: "Mecanic.D/Manuten.Montad.Etc "},
        {id: "10059", label: "Mecanica "},
        {id: "5224", label: "Mecanico De Motores Deaeronaves E De Embarcacoes "},
        {id: "541", label: "Mecanicod/Manuten.Veicul.Auto "},
        {id: "74110", label: "Mecanicos Deinstrumentos De Precisao "},
        {id: "91930", label: "Mecanicos Demanutencao De Bicicletas E Equipamentosesportivose De Ginastica "},
        {id: "91110", label: "Mecanicos Demanutencao De Bombas, Motores, Compressores E Equipamentos De Transmissao "},
        {id: "91130", label: "Mecanicos Demanutencao De Maquinas Industriais "},
        {id: "91310", label: "Mecanicos Demanutencao De Maquinas Pesadas E Equipamentosagricolas"},
        {id: "91420", label: "Mecanicos Demanutencao De Motores E Equipamentos Navais "},
        {id: "91120", label: "Mecanicos Demanutencao E Instalacao De Aparelhos Declimatizacao E Refrigeracao "},
        {id: "91430", label: "Mecanicos Demanutencao Metroferroviaria "},
        {id: "72540", label: "Mecanicos Montadoresde Motores E Turboalimentadores "},
        {id: "111", label: "Medico "},
        {id: "22530", label: "Medicos Em Medicinadiagnostica E Terapeutica "},
        {id: "22520", label: "Medicos Emespecialidades Cirurgicas "},
        {id: "203", label: "Membros Do Poder Executivo "},
        {id: "205", label: "Membros Do Poder Judiciário "},
        {id: "201", label: "Membros Do Poder Legislativo "},
        {id: "15", label: "Menor "},
        {id: "10064", label: "Mergulhador Com Equip.De Respiracao Acima 80 Mt "},
        {id: "10060", label: "Mergulhador Com Equip.De Respiracao Ate 20 Mt "},
        {id: "10061", label: "Mergulhador Com Equip.De Respiracao Ate 21-40 Mt "},
        {id: "10062", label: "Mergulhador Com Equip.De Respiracao Ate 41-60 Mt "},
        {id: "10063", label: "Mergulhador Com Equip.De Respiracao Ate 61-80 Mt "},
        {id: "16", label: "Mergulhador Profissional "},
        {id: "10065", label: "Mergulhadores - Semequipamento De Respiracao "},
        {id: "9264", label: "Mestre De Obras "},
        {id: "10067", label: "Metalurgia Do Po "},
        {id: "10066", label: "Metalurgicos (Excetofuncionarios Administradores "},
        {id: "295", label: "Militar Em Geral "},
        {id: "921", label: "Militar Reformado "},
        {id: "5245", label: "Minerador "},
        {id: "492", label: "Modelo De Modas "},
        {id: "72520", label: "Montadores De Maquinasindustriais "},
        {id: "72530", label: "Montadores De Maquinaspesadas E Agricolas"},
        {id: "77410", label: "Montadores De Moveis Eartefatos De Madeira "},
        {id: "72560", label: "Montadores De Sistemase Estruturas De Aeronaves "},
        {id: "72550", label: "Montadores De Veiculosautomotores (Linha De Montagem "},
        {id: "73110", label: "Montadores Deequipamentos Eletroeletronicos "},
        {id: "71530", label: "Montadores Deestruturas De Concreto Armado "},
        {id: "72510", label: "Montadores Demaquinas, Aparelhos E Acessorios Em Linhas Demontagem"},
        {id: "10068", label: "Montagem De Tenda "},
        {id: "51310", label: "Mordomos E Governantas "},
        {id: "10069", label: "Moto Velocidade "},
        {id: "10070", label: "Motocross "},
        {id: "532", label: "Motoris.Veicul.Transp.Decarga "},
        {id: "531", label: "Motoris.Veicul.Transp.Passage "},
        {id: "18", label: "Motorista De Veiculoveículo Detransporte De Carga Inflamavel E Quimica "},
        {id: "78230", label: "Motoristas De Veiculosde Pequeno E Medio Porte "},
        {id: "164", label: "Musico "},
        {id: "55", label: "Nutricionista "},
        {id: "10072", label: "Oceanografos "},
        {id: "115", label: "Odontólogo "},
        {id: "216", label: "Oficiais Das Forças Armadas (Exército, Marinha E Aeronáutica) Eforças Auxiliares "},
        {id: "21520", label: "Oficiais De Maquinasda Marinha Mercante "},
        {id: "1010", label: "Oficiais Generais Dasforcas Armadas "},
        {id: "2010", label: "Oficiais Superiores Dapolicia Militar "},
        {id: "167", label: "Operador D/Câmera/Cinema,Tv "},
        {id: "54", label: "Operador De Maquinas Industriais "},
        {id: "76120", label: "Operadores Da Fiacao "},
        {id: "82120", label: "Operadores De Fornosde Primeira Fusao E Aciaria "},
        {id: "77340", label: "Operadores De Maquinade Usinar Madeira (Producao Em Serie"},
        {id: "77320", label: "Operadores De Maquinasde Aglomeracao E Prensagem Chapas"},
        {id: "72450", label: "Operadores De Maquinasde Conformacao De Metais "},
        {id: "76420", label: "Operadores De Maquinasde Costurar E Montar Calcados "},
        {id: "77350", label: "Operadores De Maquinasde Usinagem De Madeira Cnc "},
        {id: "78210", label: "Operadores De Maquinase Equipamentos De Elevacao "},
        {id: "81180", label: "Operadores De Maquinase Instalacoes De Produtosfarmaceuticos,Cosmeticos E Afins "},
        {id: "76530", label: "Operadores De Maquinasna Confeccao De Artefatos Couro"},
        {id: "83310", label: "Operadores De Maquinasna Fabricacao De Produtos De Papel Epapelao"},
        {id: "76330", label: "Operadores De Maquinaspara Bordado E Acabamento Roupas"},
        {id: "37220", label: "Operadores De Rede Deteleprocessamento E Afins "},
        {id: "76130", label: "Operadores De Tear Emaquinas Similares "},
        {id: "78260", label: "Operadores De Veiculossobre Trilhos E Cabos Aereos "},
        {id: "78130", label: "Operadores De Veiculossubaquaticos Controlados Remotamente"},
        {id: "81120", label: "Operadores Decalcinacao E De Tratamentos Quimicos De MateriaisRadioativos "},
        {id: "82140", label: "Operadores Deequipamentos De Acabamento De Chapas E Metais"},
        {id: "81140", label: "Operadores Deequipamentos De Destilacao, Evaporacao Ereacao"},
        {id: "41210", label: "Operadores Deequipamentos De Entrada e Dedados"},
        {id: "82320", label: "Operadores Deequipamentos De Fabricacao E Beneficiamento DeCristais, Vidros, Ceramicas,Porcelanas, Fibras De Vidro, Abrasivos Afins"},
        {id: "81130", label: "Operadores Deequipamentos De Filtragem E Separacao "},
        {id: "82130", label: "Operadores Deequipamentos De Laminacao "},
        {id: "81110", label: "Operadores Deequipamentos De Moagem E Mistura DeMateriais(Tratamentos Quimicos E Afins "},
        {id: "78220", label: "Operadores Deequipamentos De Movimentacao De Cargas "},
        {id: "81150", label: "Operadores Deequipamentos De Producao E Refino De Petroleoe Gas"},
        {id: "86230", label: "Operadores Deinstalacoes De Captacao E Esgotos "},
        {id: "86220", label: "Operadores Deinstalacoes De Captacao, Tratamento E Distribuicao DeAgua "},
        {id: "86120", label: "Operadores Deinstalacoes De Distribuicao Energia Eletrica"},
        {id: "86240", label: "Operadores Deinstalacoes De Extracao, Processamento,Envasamento EDistribuicao De Gases "},
        {id: "86110", label: "Operadores Deinstalacoes De Geracao E Distribuicao De EnergiaEletrica, Hidraulica, Termicaou Nuclear "},
        {id: "86250", label: "Operadores Deinstalacoes De Refrigeracao E Condicionado"},
        {id: "82110", label: "Operadores Deinstalacoes De Sinterizacao "},
        {id: "82330", label: "Operadores Deinstalacoes E Equipamentos De Fabricacao De MateriaisDe Construcao "},
        {id: "10107", label: "Operadores Demaquinaria Pesada "},
        {id: "10073", label: "Operadores Demoto-Serra, Serra Eletrica Assemelhados"},
        {id: "42220", label: "Operadores Detelefonia "},
        {id: "42230", label: "Operadores Detelemarketing "},
        {id: "82310", label: "Operadores Napreparacao De Massas Para Abrasivo, Vidro,Ceramica,Porcelana E Materiais Deconstrucao "},
        {id: "22610", label: "Osteopatas Equiropraxistas "},
        {id: "51990", label: "Outros Trabalhadoresdos Servicos "},
        {id: "84830", label: "Padeiros, Confeiteirose Afins "},
        {id: "10075", label: "Pecuarista Demais "},
        {id: "10074", label: "Pecuarista Suinos "},
        {id: "5216", label: "Pedreiro,Pintor "},
        {id: "924", label: "Pensionista "},
        {id: "10130", label: "Peoes De Rodeio,Vaquejada E Similares Que Instrutores"},
        {id: "21", label: "Perito Criminal "},
        {id: "10076", label: "Peritos Policiais "},
        {id: "10079", label: "Pescadores - Barcos&Gt; 41 Mts De Comp "},
        {id: "10077", label: "Pescadores - Barcos&Lt; 24 Mts De Comp "},
        {id: "10078", label: "Pescadores - Barcos&Lt; 24-40 Mts De Comp "},
        {id: "10080", label: "Pescadores - Lagos Erios "},
        {id: "10081", label: "Pescadores Submarinos(Profissionais Ou Amadores "},
        {id: "20300", label: "Pesquisadores Dasciencias Biologicas "},
        {id: "20340", label: "Pesquisadores Dasciencias Da Agricultura "},
        {id: "20330", label: "Pesquisadores Dasciencias Da Saude "},
        {id: "20310", label: "Pesquisadores Dasciencias Naturais E Exatas "},
        {id: "20350", label: "Pesquisadores Dasciencias Sociais E Humanas "},
        {id: "20320", label: "Pesquisadores Deengenharia E Tecnologia "},
        {id: "22", label: "Petroleiro Que Exerceatividade Na Producao De Petroleo"},
        {id: "10082", label: "Piloto De Rally "},
        {id: "34110", label: "Pilotos De Aviacao comercial, Mecanicos De Voo Afins"},
        {id: "341105", label: "Pilotos De Aviação comercial, Mecânicos De Vôo E Afins-ExcetoAgrícola "},
        {id: "71660", label: "Pintores De Obras Erevestidores De Interiores(RevestimentosFlexiveis "},
        {id: "322110", label: "Podólogo "},
        {id: "10084", label: "Policiais Civis,Militares, Rodoviarios, Etc"},
        {id: "10085", label: "Policial Reformado "},
        {id: "501", label: "Porteirod/Edificio,Ascensori "},
        {id: "1030", label: "Pracas Das Forcasarmadas "},
        {id: "5228", label: "Prat. Instr. De Balao "},
        {id: "5229", label: "Prat. Instr. Dealpinismo "},
        {id: "5248", label: "Prat. Instr. Deparapent "},
        {id: "5227", label: "Prat. Instr. Deultraleve "},
        {id: "5235", label: "Pratic.Esportes Veic.Eembarc "},
        {id: "10114", label: "Praticante De Corridasde Cavalo "},
        {id: "5215", label: "Praticante De Esgrima "},
        {id: "29", label: "Praticante De Montainbikeamador Ou Profissional, Ainda Queinstrutor"},
        {id: "5232", label: "Praticante De Rafting "},
        {id: "10086", label: "Praticante Deatividades Subaquaticas "},
        {id: "10087", label: "Praticante Ouinstrutor De Asa Delta "},
        {id: "10088", label: "Praticante Ouinstrutor De Paraquedas "},
        {id: "10115", label: "Praticantes De Hipismoem Carater Profissional Amador"},
        {id: "10090", label: "Praticantes De Rapel(Por Prazer, Mais De 5 Vezes Por Ano "},
        {id: "10091", label: "Praticantes De Rapel(Por Prazer, Menos De 5 Vezes Por Ano"},
        {id: "10089", label: "Praticantes Demotonautica (Competicoes Nacionais "},
        {id: "10092", label: "Praticantes Detriatlon (Amadores E Profissionais "},
        {id: "83110", label: "Preparadores De Pastapara Fabricacao De Papel "},
        {id: "72120", label: "Preparadores Eoperadores De Ferramenta convencionais"},
        {id: "211", label: "Procurador E Assemelhados "},
        {id: "10093", label: "Producao De Gusa "},
        {id: "61210", label: "Produtores Agricolasna Cultura De Gramineas "},
        {id: "61260", label: "Produtores Agricolasna Cultura De Estimulantes"},
        {id: "61220", label: "Produtores Agricolasna Cultura De Plantas Fibrosas "},
        {id: "61270", label: "Produtores Agricolasna Cultura De Oleaginosas"},
        {id: "61250", label: "Produtores Agricolasna Fruticultura "},
        {id: "61230", label: "Produtores Agricolasna Olericultura "},
        {id: "61240", label: "Produtores Agricolasno Cultivo De Flores e Ornamentais"},
        {id: "61330", label: "Produtores Daavicultura E Cunicultura "},
        {id: "61340", label: "Produtores De Animaise Insetos Uteis "},
        {id: "61280", label: "Produtores Deespeciarias E De Plantas Aromaticas Medicinais"},
        {id: "61310", label: "Produtores Em Pecuariade Animais De Grande Porte "},
        {id: "61320", label: "Produtores Em Pecuariade Animais De Medio Porte "},
        {id: "143", label: "Prof./Ensino D/1o.E2o.Graus "},
        {id: "142", label: "Professor De Ensino Superior "},
        {id: "23490", label: "Professores De Artesdo Ensino Superior "},
        {id: "33110", label: "Professores De Nivelmedio Na Educacao Infantil "},
        {id: "33120", label: "Professores De Nivelmedio No Ensino Fundamental "},
        {id: "33130", label: "Professores De Nivelmedio No Profissionalizante"},
        {id: "23110", label: "Professores De Nivelsuperior Na Educacao Infantil "},
        {id: "23130", label: "Professores De Nivelsuperior No Ensino Fundamental De Quinta A Oitava Serie "},
        {id: "23430", label: "Professores Dearquitetura E Urbanismo,Engenharia,Geofisica E Geologia Do Ensino Superior "},
        {id: "23440", label: "Professores Deciencias Biologicas E Da Saude Doensinosuperior"},
        {id: "23480", label: "Professores Deciencias Economicas, Administrativasecontabeis Do Ensino Superior "},
        {id: "23420", label: "Professores Deciencias Fisicas, Quimicas E Afins Doensinosuperior"},
        {id: "23470", label: "Professores Deciencias Humanas Do Ensino Superior "},
        {id: "23920", label: "Professores Deeducacao Especial "},
        {id: "23310", label: "Professores Do Ensinoprofissional "},
        {id: "33210", label: "Professores Leigos Noensino Fundamental "},
        {id: "23450", label: "Professores Na Area Deformacao Pedagogica Doensinosuperior"},
        {id: "23460", label: "Professores Nas Areasde Lingua E Literatura Doensinosuperior"},
        {id: "33220", label: "Professores Praticosno Ensino Profissionalizante "},
        {id: "10094", label: "Profis. Que Executematividades A Bordo De Balancins "},
        {id: "25260", label: "Profissionais Daadministracao Dos Servicos De Seguranca "},
        {id: "20110", label: "Profissionais Dabiotecnologia "},
        {id: "22410", label: "Profissionais Daeducacao Fisica "},
        {id: "26150", label: "Profissionais Daescrita "},
        {id: "25450", label: "Profissionais Dafiscalizacao De Atividades Urbanas "},
        {id: "24290", label: "Profissionais Dainteligencia "},
        {id: "20120", label: "Profissionais Dametrologia "},
        {id: "22630", label: "Profissionais Dasterapias Criativas,Equoterapicasenaturologicas "},
        {id: "25250", label: "Profissionais Deadministracao Economico-Financeira "},
        {id: "25320", label: "Profissionais Decomercializacao E Consultoria De Servicosbancarios"},
        {id: "35240", label: "Profissionais Dedireitos Autorais E De Avaliacao De Produtos Dos Meios De Comunicacao "},
        {id: "25240", label: "Profissionais Derecursos Humanos "},
        {id: "51980", label: "Profissionais Do Sexo "},
        {id: "138", label: "Profissional D/Letras E Artes "},
        {id: "57", label: "Programador "},
        {id: "23940", label: "Programadores,Avaliadores E Orientadores De Ensino "},
        {id: "56", label: "Promotor De Justica "},
        {id: "906", label: "Prop.D/Imovel,Rec.Rend.Aluguel "},
        {id: "901", label: "Prop.Estab.Agricola,Pecu.Flor "},
        {id: "904", label: "Prop.Estab.Prestacaod/Servico "},
        {id: "10096", label: "Proponentes Sem Rendapropria "},
        {id: "903", label: "Propriet.Estabeleci.Industrial "},
        {id: "902", label: "Propriet.Estabelecim.Comercial "},
        {id: "905", label: "Proprietario Demicroempresa "},
        {id: "10097", label: "Provas Com Carro Oumoto "},
        {id: "132", label: "Psicólogo "},
        {id: "172", label: "Publicitário "},
        {id: "104", label: "Químico "},
        {id: "5172", label: "Quimico Industrial "},
        {id: "42210", label: "Recepcionistas "},
        {id: "37140", label: "Recreadores "},
        {id: "5202", label: "Regulador Intern. Desinistros "},
        {id: "137", label: "Relações Publicas "},
        {id: "95420", label: "Reparadores Deaparelhos Eletrodomesticos "},
        {id: "95430", label: "Reparadores Deequipamentos De Escritorio "},
        {id: "91540", label: "Reparadores Deequipamentos Fotograficos "},
        {id: "58", label: "Representante Comercial "},
        {id: "5203", label: "Ressarcidor "},
        {id: "91520", label: "Restauradores Deinstrumentos Musicais "},
        {id: "71610", label: "Revestidores Deconcreto "},
        {id: "910", label: "Sacerdote/Memb.Ordensseit.Rel "},
        {id: "393", label: "Secretario, Estenografo, Datilo "},
        {id: "396", label: "Securitário "},
        {id: "10101", label: "Seguranca/Vigilante(Exceto Tecnicos De Segurancanotrabalho"},
        {id: "5211", label: "Serralheiro "},
        {id: "293", label: "Serventuário De Justiça "},
        {id: "10098", label: "Servicos De Entrega -Em Automoveis E Caminhoes "},
        {id: "10099", label: "Servicos De Entrega -Em Moto (Motoboy "},
        {id: "5191", label: "Sindicante "},
        {id: "133", label: "Sociólogo "},
        {id: "10100", label: "Soldadores "},
        {id: "75210", label: "Sopradores, Moldadorese Modeladores De Vidros Afins"},
        {id: "2110", label: "Subtenentes E Sargentosda Policia Militar "},
        {id: "401", label: "Supervis.Inspetor, Agen. Compras "},
        {id: "76050", label: "Supervisores Daconfeccao De Artefatos De Tecidos, Couros E Afins"},
        {id: "71010", label: "Supervisores Daextracao Mineral "},
        {id: "84010", label: "Supervisores Dafabricacao De Alimentos, Bebidas Fumo"},
        {id: "83010", label: "Supervisores Dafabricacao De Celulose E Papel "},
        {id: "72020", label: "Supervisores Dafabricacao E Montagem Metalmecanica "},
        {id: "76010", label: "Supervisores Daindustria Textil "},
        {id: "74010", label: "Supervisores Damecanica De Precisao Instrumentosmusicais"},
        {id: "86010", label: "Supervisores Daproducao De Utilidades "},
        {id: "76060", label: "Supervisores Das Artesgraficas "},
        {id: "91090", label: "Supervisores De Outrostrabalhadores De Servicos Dereparacao,Conservacao E Manutencao "},
        {id: "52010", label: "Supervisores De Vendase De Prestacao De Servicos "},
        {id: "42010", label: "Supervisores Deatendimento Ao Publico E De Pesquisa "},
        {id: "75010", label: "Supervisores Dejoalheria E Afins "},
        {id: "51020", label: "Supervisores Delavanderia "},
        {id: "95020", label: "Supervisores Demanutencao Eletroeletronica Veicular "},
        {id: "95010", label: "Supervisores Demanutencao Eletroeletronicaindustrial,Comercial EPredial "},
        {id: "95030", label: "Supervisores Demanutencao Eletromecanica "},
        {id: "73010", label: "Supervisores Demontagens e Eletroeletronicas"},
        {id: "81030", label: "Supervisores Deproducao Em Industrias De Produtos Farmaceuticos,Cosmeticos E Afins "},
        {id: "81020", label: "Supervisores Deproducao Em Industrias De TransformacaodeplasticosE Borrachas "},
        {id: "82010", label: "Supervisores Deproducao Em Industrias Siderurgicas "},
        {id: "81010", label: "Supervisores Deproducao Em Industriasquimicas,Petroquimicas EAfins "},
        {id: "41020", label: "Supervisores Deservicos Financeiros, de Cambio de Controle"},
        {id: "78010", label: "Supervisores Detrabalhadores De Embalagem Etiquetagem"},
        {id: "72010", label: "Supervisores Deusinagem, Conformacao e de metais"},
        {id: "75020", label: "Supervisores Devidraria, Ceramica E Afins "},
        {id: "51010", label: "Supervisores Dosservicos De Transporte, Turismo,Hotelariaeadministracao De Edificios "},
        {id: "77010", label: "Supervisores Emindustria De Madeira, Mobiliario E DacarpintariaVeicular "},
        {id: "91010", label: "Supervisores Emservicos De Reparacao E Manutencao Demaquinas EEquipamentos Industriais,Comerciais E Residenciais "},
        {id: "63010", label: "Supervisores Na Areaflorestal E Aquicultura "},
        {id: "76040", label: "Supervisores Naconfeccao De Calcados "},
        {id: "76030", label: "Supervisores Naconfeccao Do Vestuario "},
        {id: "62010", label: "Supervisores Naexploracao Agropecuaria "},
        {id: "82020", label: "Supervisores Nafabricacao De Materiais Para Construcao(Vidros ECeramicas "},
        {id: "76020", label: "Supervisores Naindustria Do Curtimento "},
        {id: "41010", label: "Supervisoresadministrativos "},
        {id: "5231", label: "Surfista "},
        {id: "294", label: "Tabelião "},
        {id: "10112", label: "Taekwondo "},
        {id: "156", label: "Técn./Eletri.Eletro.Telecom "},
        {id: "157", label: "Técn./Laboratório E Raios X "},
        {id: "153", label: "Técnico Agronomia, Agrimensura "},
        {id: "151", label: "Tecnico D/Contabil.Eestatist "},
        {id: "152", label: "Técnico De Biologia "},
        {id: "64", label: "Tecnico De Enfermagem "},
        {id: "59", label: "Técnico De Informática "},
        {id: "155", label: "Técnico De Mecânica "},
        {id: "154", label: "Técnico De Química "},
        {id: "5219", label: "Tecnico De Seguranca "},
        {id: "32510", label: "Tecnico Em Farmacia Eem Manipulacao Farmaceutica "},
        {id: "322105", label: "Tecnico Emacupuntura/Acupuntor "},
        {id: "30120", label: "Tecnicos De Apoio Abioengenharia "},
        {id: "32530", label: "Tecnicos De Apoio Abiotecnologia "},
        {id: "39510", label: "Tecnicos De Apoio Empesquisa E Desenvolvimento "},
        {id: "39120", label: "Tecnicos De Controleda Producao "},
        {id: "37310", label: "Tecnicos De Operacaode Emissoras De Radio "},
        {id: "32260", label: "Tecnicos Deimobilizacoes Ortopedicas "},
        {id: "32420", label: "Tecnicos Delaboratorios De Saude E Bancos De Sangue "},
        {id: "32240", label: "Tecnicos Deodontologia "},
        {id: "31920", label: "Tecnicos Do Mobiliarioe Afins "},
        {id: "31910", label: "Tecnicos Do Vestuario "},
        {id: "37410", label: "Tecnicos Em Audio "},
        {id: "31340", label: "Tecnicos Em Calibracaoe Instrumentacao "},
        {id: "37420", label: "Tecnicos Em Cenografia "},
        {id: "31210", label: "Tecnicos Em Construcaocivil (Edificacoes "},
        {id: "31220", label: "Tecnicos Em Construcaocivil (Obras De Infraestrutura "},
        {id: "31150", label: "Tecnicos Em Controleambiental, Utilidades E Tratamento DeEfluentes "},
        {id: "31350", label: "Tecnicos Em Fotonica "},
        {id: "31230", label: "Tecnicos Em Geomatica "},
        {id: "91530", label: "Tecnicos Em Manutencaoe Reparacao De Equipamentosbiomedicos"},
        {id: "91510", label: "Tecnicos Em Manutencaoe Reparacao De Instrumentos Demedicao EPrecisao "},
        {id: "31130", label: "Tecnicos Em Materiais,Produtos Ceramicos E Vidros "},
        {id: "31430", label: "Tecnicos Em Mecanicaveicular "},
        {id: "37440", label: "Tecnicos Em Montagem,Edicao E Finalizacao De Filme Video"},
        {id: "37120", label: "Tecnicos Em Museologiae Afins "},
        {id: "32810", label: "Tecnicos Em Necropsiae Taxidermistas "},
        {id: "37430", label: "Tecnicos Em Operacaode Aparelhos De Projecao "},
        {id: "37320", label: "Tecnicos Em Operacaode Sistemas De Televisao E Deprodutoras DeVideo "},
        {id: "32230", label: "Tecnicos Em Optica Eoptometria "},
        {id: "32310", label: "Tecnicos Em Pecuaria "},
        {id: "32520", label: "Tecnicos Em Producao,Conservacao e de alimentos"},
        {id: "32250", label: "Tecnicos Em Protesesortopedicas "},
        {id: "31470", label: "Tecnicos Em Siderurgia "},
        {id: "35130", label: "Tecnicos Emadministracao "},
        {id: "32130", label: "Tecnicos Emaquicultura "},
        {id: "37110", label: "Tecnicos Embiblioteconomia "},
        {id: "31310", label: "Tecnicos Emeletricidade E Eletrotecnica "},
        {id: "30030", label: "Tecnicos Emeletromecanica "},
        {id: "30010", label: "Tecnicos Emmecatronica "},
        {id: "35150", label: "Tecnicos Emsecretariado, Taquigrafos Estenotipistas"},
        {id: "31330", label: "Tecnicos Emtelecomunicacoes "},
        {id: "34250", label: "Tecnicos Emtransportes Aereos "},
        {id: "34240", label: "Tecnicos Emtransportes Metroferroviarios "},
        {id: "34260", label: "Tecnicos Emtransportes Por Vias Navegaveis E Operacoesportuarias"},
        {id: "34230", label: "Tecnicos Emtransportes Rodoviarios "},
        {id: "32120", label: "Tecnicos Florestais "},
        {id: "34130", label: "Tecnicos Maritimos Efluviarios De Maquinas "},
        {id: "31440", label: "Tecnicos Mecanicos Namanutencao De Maquinas, Sistemas EInstrumentos "},
        {id: "31420", label: "Tecnicos Mecanicos(Ferramentas "},
        {id: "31160", label: "Tecnicos Texteis "},
        {id: "108", label: "Tecnólogo "},
        {id: "32410", label: "Tecnologos E Tecnicosem Metodos De Diagnosticos Terapeutica"},
        {id: "10102", label: "Telhadistas,Antenistas, Atividades Executadas Telhados"},
        {id: "71620", label: "Telhadores(Revestimentos Rigidos "},
        {id: "2030", label: "Tenentes Da Policiamilitar "},
        {id: "22390", label: "Terapeutasocupacionais E Ortoptistas "},
        {id: "51630", label: "Tintureiros,Lavadeiros E Afins, A Maquina "},
        {id: "10126", label: "Trab. Em Mineracao,Explosao De Pedreiras,Perfuracoes,Demolicoes EImplosoes "},
        {id: "710", label: "Trab.D/Fabr.Eprepara.D/Alim "},
        {id: "704", label: "Trab.D/Instal.D/Proces.Quimico "},
        {id: "706", label: "Trab.D/Tratam.Fumo,Fabr.Cigar "},
        {id: "715", label: "Trab.Fabr.Calcadosartef.Couro "},
        {id: "713", label: "Trab.Fabr.D/ Artefatosmadeira "},
        {id: "712", label: "Trab.Fabr.De Produtostexteis "},
        {id: "716", label: "Trab.Fabr.Prod.Borracha,Plast "},
        {id: "714", label: "Trab.Fabric.D/Papel Epapelao "},
        {id: "707", label: "Trab.Metalurgico Esiderurgic "},
        {id: "145", label: "Trab.Niveltrab. Nível Sup.Ligasup. Liga Dos Ensinos"},
        {id: "705", label: "Trabalh.D/Fabricacao Deroupas "},
        {id: "708", label: "Trabalhad.D/Usinagemd/Metais "},
        {id: "601", label: "Trabalhador Agricola "},
        {id: "709", label: "Trabalhador D/Construcaocivil "},
        {id: "392", label: "Trabalhador D/Servicoscontab "},
        {id: "602", label: "Trabalhador Da Pecuaria "},
        {id: "604", label: "Trabalhador Da Pesca "},
        {id: "711", label: "Trabalhador De Artesgraficas "},
        {id: "36", label: "Trabalhador De Qualqueratividade Referente A Industrial"},
        {id: "37", label: "Trabalhador E Operador Demoto Serra, Serra e Assemelhados- "},
        {id: "603", label: "Trabalhador Florestal "},
        {id: "76110", label: "Trabalhadores Daclassificacao De Fibras Texteis E La"},
        {id: "51920", label: "Trabalhadores Dacoleta E Selecao de Reciclavel- "},
        {id: "76520", label: "Trabalhadores Daconfeccao De Artefatos De Tecidos, CouroseSinteticos "},
        {id: "71130", label: "Trabalhadores Daextracao De Minerais Liquidos Gasosos"},
        {id: "82810", label: "Trabalhadores Dafabricacao De Ceramica Estruturalparaconstrucao"},
        {id: "76620", label: "Trabalhadores Daimpressao Grafica "},
        {id: "84110", label: "Trabalhadores Daindustria De Beneficiamento De Graos,CereaisEafins "},
        {id: "64300", label: "Trabalhadores Dairrigacao E Drenagem "},
        {id: "64100", label: "Trabalhadores Damecanizacao Agricola "},
        {id: "64200", label: "Trabalhadores Damecanizacao Florestal "},
        {id: "72330", label: "Trabalhadores Dapintura De Equipamentos, Veiculos,EstruturasMetalicas E De Compositos "},
        {id: "76610", label: "Trabalhadores Dapre-Impressao Grafica "},
        {id: "76410", label: "Trabalhadores Dapreparacao Da Confeccao De Calcados "},
        {id: "76510", label: "Trabalhadores Dapreparacao De Artefatos De Tecidos, CouroseTapecaria "},
        {id: "76210", label: "Trabalhadores Dapreparacao Do Curtimento De Couros Peles"},
        {id: "75220", label: "Trabalhadores Datransformacao De Vidros Planos "},
        {id: "77510", label: "Trabalhadores De Artee Do Acabamento Madeira do Mobiliario"},
        {id: "76430", label: "Trabalhadores Deacabamento De Calcados "},
        {id: "76140", label: "Trabalhadores Deacabamento, Tingimento E Estamparia Das IndustriasTexteis "},
        {id: "51530", label: "Trabalhadores Deatencao, Defesa E Protecao A Pessoas Em SituacaoDe Risco E Adolescentes Emconflito Com A Lei "},
        {id: "71220", label: "Trabalhadores Debeneficiamento De Pedras Ornamentais "},
        {id: "78410", label: "Trabalhadores Deembalagem E De Etiquetagem "},
        {id: "71120", label: "Trabalhadores Deextracao De Minerais Solidos (OperadoresdeMaquinas "},
        {id: "72210", label: "Trabalhadores Deforjamento De Metais "},
        {id: "72220", label: "Trabalhadores Defundicao De Metais Puros E Ligas Metalicas"},
        {id: "76640", label: "Trabalhadores Delaboratorio Fotografico Radiologico"},
        {id: "78310", label: "Trabalhadores Demanobras De Transportes Sobre Trilhos "},
        {id: "91920", label: "Trabalhadores Demanutencao De Rocadeiras, Motoserrasesimilares"},
        {id: "72230", label: "Trabalhadores Demoldagem De Metais e de Metalicas"},
        {id: "51930", label: "Trabalhadores Deservicos Veterinarios, De Higiene E Estetica DeAnimais Domesticos "},
        {id: "76810", label: "Trabalhadores Detecelagem Manual, Trico, Rendaseafins"},
        {id: "72320", label: "Trabalhadores Detratamento De Superficies De Metais E Decompositos(Termoquimicos "},
        {id: "77210", label: "Trabalhadores Detratamento E Preparacao Da Madeira "},
        {id: "72310", label: "Trabalhadores Detratamento Termico De Metais "},
        {id: "72240", label: "Trabalhadores Detrefilacao E Estiramento De Metais Puros E LigasMetalicas "},
        {id: "76540", label: "Trabalhadores Doacabamento De Artefatos de e Couros"},
        {id: "76230", label: "Trabalhadores Doacabamento De Couros E Peles "},
        {id: "76630", label: "Trabalhadores Doacabamento Grafico "},
        {id: "76220", label: "Trabalhadores Docurtimento De Couros E Peles "},
        {id: "51510", label: "Trabalhadores Emservicos De Promocao E Apoio A Saude "},
        {id: "62330", label: "Trabalhadores Naavicultura E Cunicultura "},
        {id: "62340", label: "Trabalhadores Nacriacao De Insetos E Animais Uteis "},
        {id: "84840", label: "Trabalhadores Nadegustacao E Classificacao de e Afins- "},
        {id: "84170", label: "Trabalhadores Nafabricacao De Cachaca, Cerveja, Vinhos EoutrasBebidas "},
        {id: "84140", label: "Trabalhadores Nafabricacao E Conservacao Alimentos"},
        {id: "84130", label: "Trabalhadores Nafabricacao E Refino De Acucar "},
        {id: "84160", label: "Trabalhadores Naindustrializacao De Cafe, Cacau, Mate EdeprodutosAfins "},
        {id: "84150", label: "Trabalhadores Napasteurizacao Do Leite E Na Fabricacao DeLaticinios E Afins "},
        {id: "62320", label: "Trabalhadores Napecuaria De Animais De Medio Porte "},
        {id: "84120", label: "Trabalhadores Nobeneficiamento Do Sal "},
        {id: "51410", label: "Trabalhadores Nosservicos De Administracao Edificios"},
        {id: "41520", label: "Trabalhadores Nosservicos De Classificacao EEntregasdecorrespondencias, Encomendas Epublicacoes "},
        {id: "62280", label: "Trabalhadoresagricolas Da Cultura De Especiarias E De PlantasAromaticas E Medicinais "},
        {id: "62220", label: "Trabalhadoresagricolas Na Cultura de Fibrosas"},
        {id: "62270", label: "Trabalhadoresagricolas Na Cultura De Oleaginosas"},
        {id: "62250", label: "Trabalhadoresagricolas Na Fruticultura "},
        {id: "62230", label: "Trabalhadoresagricolas Na Olericultura "},
        {id: "62260", label: "Trabalhadoresagricolas Nas Culturas Plantas Estimulantes"},
        {id: "62240", label: "Trabalhadoresagricolas No Cultivo De Flores E Plantas Ornamentais"},
        {id: "76830", label: "Trabalhadoresartesanais Da Confeccao De Calcados Eartefatos DeCouros E Peles "},
        {id: "76820", label: "Trabalhadoresartesanais Da Confeccao De Pecas Tecidos"},
        {id: "83320", label: "Trabalhadoresartesanais De Produtos De Papel Papelao"},
        {id: "84810", label: "Trabalhadoresartesanais Na Conservacao De Alimentos "},
        {id: "84820", label: "Trabalhadoresartesanais Na Pasteurizacao Do Leite E Na FabricacaoDe Laticinios E Afins "},
        {id: "51660", label: "Trabalhadoresauxiliares Dos Servicos Funerarios "},
        {id: "51350", label: "Trabalhadoresauxiliares Nos Servicos De Alimentacao "},
        {id: "99210", label: "Trabalhadoreselementares De Servicos Manutencao Veicular"},
        {id: "63200", label: "Trabalhadoresflorestais Polivalentes "},
        {id: "99220", label: "Trabalhadoresoperacionais De Conservacao De Viaspermanentes(ExcetoTrilhos "},
        {id: "76500", label: "Trabalhadorespolivalentes Da Confeccao De Artefatos De Tecidos ECouros "},
        {id: "76200", label: "Trabalhadorespolivalentes Do Curtimento De Couros Peles"},
        {id: "76860", label: "Trabalhadorestipograficos Linotipistas E Afins "},
        {id: "5243", label: "Trabalhadorsubst.Toxicas "},
        {id: "5201", label: "Tradutor "},
        {id: "72460", label: "Trancadores E Laceirosde Cabos De Aco "},
        {id: "10104", label: "Transporte De Gado "},
        {id: "10127", label: "Transporte De Pessoas(Taxi, Onibus "},
        {id: "10105", label: "Transporte Demercadorias Nao Perigosas "},
        {id: "10106", label: "Transporte Espacial "},
        {id: "411", label: "Vendedorcomerci.Varejis.Ataca "},
        {id: "52430", label: "Vendedores Ambulantes "},
        {id: "52410", label: "Vendedores Emdomicilio "},
        {id: "402", label: "Vendedorpracista, Repres. Comer "},
        {id: "112", label: "Veterinário "},
        {id: "5210", label: "Vidraceiro "},
        {id: "75240", label: "Vidreiros E Ceramistas(Arte E Decoracao) "},
        {id: "55559", label: "Vistoriador Deveiculos "},
        {id: "39", label: "Zootecnista "},
    ];

    return (
        <Card>
            <Typography className="titlePatternOne" color="#5100ff" variant="h3" remetent="h1">
                Olá, vamos juntos encontrar o melhor seguro de vida para vc? =D
            </Typography>

            <TextField {...props.teste1} sx={{ mt: 1 }} fullWidth label="Quando você nasceu?" name="nascimento" variant="filled" />

            <Autocomplete
                {...props.teste2}
                disablePortal
                fullWidth
                sx={{ mt: 3 }}
                options={profissoes}
                renderInput={(params) => <TextField {...params} variant="filled" label="Qual a sua profissão" />}
            />

            <Typography mt={3} mb={1} color="#696969" variant="subtitle1" remetent="h1">
                Qual o seu gênero?
            </Typography>
            <RadioGroup row aria-label="genero" name="row-radio-buttons-group">
                <FormControlLabel value="masculino" control={<Radio />} label="Masculino" />
                <FormControlLabel value="feminino" control={<Radio />} label="Feminino" />
            </RadioGroup>

        </Card>
    );
}